apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  #与RBAC文件中的namespace保持一致 “ps:建议default,我尝试换成其他的命名空间但是失败了”
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: robot-nfs-storage  #provisioner名称,请确保该名称与 nfs-sc.yaml文件中的provisioner名称保持一致
            - name: NFS_SERVER
              value: 10.94.22.240   #NFS Server IP地址 server master节点的地址 换成你的主节点IP即可
            - name: NFS_PATH   
              value: /opt/nfs    #NFS挂载卷 server路径 换成你的服务器路径即可
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.94.22.240  #NFS Server IP地址
            path: /opt/nfs #NFS 挂载卷 client路径 (pod) 换成你的client路径即可，
