kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim    # 只创建一个PVC即可，该PVC与sc-pv绑定
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"   #与nfs-StorageClass.yaml metadata.name保持一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi      #所有pod公用这一个pvc即可，生产环境这里可以设置大一点
